server:
    port=8080

spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        database: 0
        timeout: 300000ms  #连接超时
        jedis:
            pool:
                max-active: 8  #连接池最大的连接数
                max-wait: -1ms  #连接池最大的阻塞等待时间（负值表示没有限制）
                max-idle: 500  #连接池最大的空闲连接

        key-prefix: 'myapp:'